<a href="https://colab.research.google.com/github/Aziyaa-Subair/learn.py/blob/main/Copy_of_TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [ ]:
#please provide your answer below this line.
from numpy import random
x = random.rand(3, 3)
print(x)



[[0.29826429 0.99076664 0.61196279]
 [0.97037419 0.58105684 0.23278071]
 [0.22867568 0.51481009 0.25773893]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [ ]:
#please provide your answer below this line.
import numpy as np
a=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
print(a)
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(b)
c=a.reshape(2,8)
d=b.reshape(2,8)
print(c)
print(d)
e=np.vstack((a,b))
print(e)
f=np.hstack((a,b))
print(f)




[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  1  1  1]
 [ 2  2  2  2]
 [ 3  3  3  3]
 [ 4  4  4  4]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  1  1  1  1  2  3  4]
 [ 2  2  2  2  5  6  7  8]
 [ 3  3  3  3  9 10 11 12]
 [ 4  4  4  4 13 14 15 16]]
