<a href="https://colab.research.google.com/github/Aziyaa-Subair/learn.py/blob/main/TASK_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a DataFrame by passing a random numpy array,with a datetie index and labelled columns.and display its,
     - Head
     - Tail
     - Index 
     - Columns
     - Values
     - statistics


In [17]:
#please type your answer below this line.
import pandas as pd
import numpy as np
dates = pd.date_range('20210901', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('1234'))
print(df)
print("\n")
print("Head")
print(df.head(1))
print("\n")
print("Tail")
print(df.tail(1))
print("\n")
print("Index")
print(df.index)
print("\n")
print("Columns")
print(df.columns)
print("\n")
print("Values")
print(df.values)
print("\n")
print("Statistics")
print(df.describe())



                   1         2         3         4
2021-09-01 -1.544537  1.154475 -0.041374  1.338251
2021-09-02 -0.659125  1.272494 -1.772470 -0.196567
2021-09-03  0.668330  0.716466  0.573456  0.836892
2021-09-04 -0.704590 -1.913300  1.323928  1.892957
2021-09-05  0.150672  0.556206 -0.423716 -0.140092
2021-09-06  0.190278 -0.383477  0.589699  0.468453


Head
                   1         2         3         4
2021-09-01 -1.544537  1.154475 -0.041374  1.338251


Tail
                   1         2         3         4
2021-09-06  0.190278 -0.383477  0.589699  0.468453


Index
DatetimeIndex(['2021-09-01', '2021-09-02', '2021-09-03', '2021-09-04',
               '2021-09-05', '2021-09-06'],
              dtype='datetime64[ns]', freq='D')


Columns
Index(['1', '2', '3', '4'], dtype='object')


Values
[[-1.54453698  1.15447498 -0.04137412  1.33825148]
 [-0.65912544  1.27249437 -1.77246994 -0.19656712]
 [ 0.66832993  0.71646615  0.57345574  0.83689217]
 [-0.70458983 -1.91329997  1.32392816 

2. Use the above table and,
      - find transpose of your data.
      - sort the index in the descending order of the date.

In [36]:
#please provide your answer below this line.
import pandas as pd
import numpy as np
dates = pd.date_range('20210901', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('1234'))
print(df)
print("\n")
print("Transpose")
print(df.T)
print("\n")
print("The index in the descending order of the date")
df.sort_index(axis=0, ascending=False)

                   1         2         3         4
2021-09-01  0.312985  0.938770  1.594607 -1.624135
2021-09-02 -0.353621 -0.098514 -0.746377 -0.814201
2021-09-03 -0.040703 -0.399904 -0.074965  0.353783
2021-09-04 -1.582265  1.858140  2.164934  1.519460
2021-09-05  0.781631  0.808867  0.643473  1.748946
2021-09-06 -0.640617 -2.034526 -0.096965  0.602943


Transpose
   2021-09-01  2021-09-02  2021-09-03  2021-09-04  2021-09-05  2021-09-06
1    0.312985   -0.353621   -0.040703   -1.582265    0.781631   -0.640617
2    0.938770   -0.098514   -0.399904    1.858140    0.808867   -2.034526
3    1.594607   -0.746377   -0.074965    2.164934    0.643473   -0.096965
4   -1.624135   -0.814201    0.353783    1.519460    1.748946    0.602943


Sort the index in the descending order of the date


1         2         3         4
2021-09-06 -0.640617 -2.034526 -0.096965  0.602943
2021-09-05  0.781631  0.808867  0.643473  1.748946
2021-09-04 -1.582265  1.858140  2.164934  1.519460
2021-09-03 -0.040703 -0.399904 -0.074965  0.353783
2021-09-02 -0.353621 -0.098514 -0.746377 -0.814201
2021-09-01  0.312985  0.938770  1.594607 -1.624135