<a href="https://colab.research.google.com/github/Aziyaa-Subair/learn.py/blob/main/TASK_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [2]:
#please type your answer below this line.
import numpy as np
mx = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(mx)
print("Trace of the matrix=")
mx.trace()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Trace of the matrix=


30

2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [3]:
#please type your answer below this line.
import numpy as np
m = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print("Matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse:")
print(result)

Matrix:
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
Inverse:
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [3]:
#please type your answer below this line.
import numpy as np
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)
a_norm=np.linalg.norm(a)
print("Norm of array=")
print(a_norm)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
Norm of array=
14.2828568570857


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [13]:
#please type your answer below this line.
import numpy as np
from numpy.linalg import eig
a=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print("Array=")
print(a)
w,v=eig(a)
print('Eigenvalue:', w)
print('Eigenvector', v)


Array=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Eigenvalue: [ 3.24642492e+01 -2.46424920e+00  2.55670932e-15 -1.93389056e-16]
Eigenvector [[-0.11417645  0.7327781  -0.54471271  0.09683789]
 [-0.3300046   0.28974835  0.76902356  0.27269982]
 [-0.54583275 -0.15328139  0.09609099 -0.8359133 ]
 [-0.76166089 -0.59631113 -0.32040185  0.46637559]]
