<a href="https://colab.research.google.com/github/Aziyaa-Subair/learn.py/blob/main/TASK_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. For the given ndarray b below, evaluate whether elements in array, b are equal to 'red'.Assign the result to b_bool and print the resultant boolean array.
b = np.array(["blue", "blue", "red", "blue"])

In [11]:
#please type your answer below this line.
import numpy as np
b=np.array(["blue","blue","red","blue"])
print(b)
b_bool=b=="red"
print(b_bool)


['blue' 'blue' 'red' 'blue']
[False False  True False]


2. Create two arrays on containing elements from 0-5 and another containing elements from 6-10. Then append this array.

In [1]:
#please type your answer below this line.
import numpy as np
ar1=np.array([0,1,2,3,4,5])
ar2=np.array([6,7,8,9,10])
ar1=np.append(ar1,ar2)
print(ar1)

[ 0  1  2  3  4  5  6  7  8  9 10]


3. Create a 2x4 array containing values from 0-7 and another 2x4 containing values from 8-15. Now append this with,

  a) axis as 0

  b) axis as 1

In [1]:
#please type your answer below this line.
import numpy as np
a=np.arange(0,8,1)
a.resize(2,4)
print("array1=")
print(a)
b=np.arange(8,16,1)
b.resize(2,4)
print("array2=")
print(b)
a=np.append(a,b,axis=0)
print("Axis as 0")
print(a)
a=np.arange(0,8,1)
a.resize(2,4)
b=np.arange(8,16,1)
b.resize(2,4)
a=np.append(a,b,axis=1)
print("Axis as 1")
print(a)


array1=
[[0 1 2 3]
 [4 5 6 7]]
array2=
[[ 8  9 10 11]
 [12 13 14 15]]
Axis as 0
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Axis as 1
[[ 0  1  2  3  8  9 10 11]
 [ 4  5  6  7 12 13 14 15]]
