<a href="https://colab.research.google.com/github/Aziyaa-Subair/learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [19]:
#please provide your answer below this line.
import numpy as np
x=np.array([[1,11,13],[12,16,5],[7,9,6]])
print(x)
y=np.array([[2,7,9],[5,9,8],[11,3,9]])
print(y)
z=np.dot(x,y)
print("Dot product")
print(z)
a=z.transpose(1,0)
print("Transpose")
print(a)


[[ 1 11 13]
 [12 16  5]
 [ 7  9  6]]
Dot product
[[ 2  7  9]
 [ 5  9  8]
 [11  3  9]]
[[200 145 214]
 [159 243 281]
 [125 148 189]]
Transpose
[[200 159 125]
 [145 243 148]
 [214 281 189]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [23]:
#please provide your answer below this line.
import numpy as np
x=np.array([[55,25,15],[30,44,2], [11,45,77]])
print(x)
d=np.linalg.det(x)
print("Determinant=")
print(int(d))

[[55 25 15]
 [30 44  2]
 [11 45 77]]
Determinant=
137180
