<a href="https://colab.research.google.com/github/Aziyaa-Subair/learn.py/blob/main/TASK_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a 3x3 array values ranging from 0-8.Find the sum of the elements in this array.

In [5]:
#please enter your code below this line.
import numpy as np
ar=np.arange(0,16,1)
newarr=ar.reshape(4,4)
print(newarr)
print("Sum of elements=")
newarr.sum()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum of elements=


120

2. Create a 3x3 array values ranging from 0-8.Find the row sum and column sum of this array.

In [11]:
#please enter your code below this line.
import numpy as np
ar=np.arange(0,9,1)
newarr=ar.reshape(3,3)
print(newarr)
sum_row=newarr.sum(axis=1)
print("Row sum")
print(sum_row)
sum_col=newarr.sum(axis=0)
print("Column sum")
print(sum_col)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Row sum
[ 3 12 21]
Column sum
[ 9 12 15]


3. Create a 4x4 array values ranging from 0-15. Now,

    a) Find the mininmum value in the array.
    
    b) Find the maximum value in the array.

    c) Find the mean of the values in the array.

In [20]:
#please enter your code belowthis line.
import numpy as np
ar=np.arange(0,16,1)
newarr=ar.reshape(4,4)
print(newarr)
min_val=newarr.min()
print(" Minimum value=",min_val)
max_val=newarr.max()
print("Maximum value=",max_val)
m_val=newarr.mean()
print("Mean value=",m_val)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
 Minimum value= 0
Maximum value= 15
Mean value= 7.5


4. Create an 10x10 array values ranging from 0-99.And ,

    a) Print the 7th row.
    
    b) Print the rows from 4-8.

    c) Print the value at the index 5,5.

    d) Print the 5th colomn.

    e) Print the columns from 2-5.

In [54]:
#please enter your code below this line.
import numpy as np
ar=np.arange(0,100,1)
a2 = ar.reshape(10,10)
print(a2)
print("7th row")
print(a2[6])
print("4th to 8th row")
print(a2[3:8])
value = a2[4,4]
print("value at the index 5,5=",value)
print("5th column")
print(a2[:,5])
print("2nd to 5th column")
c=a2[:, 1:5]
print(c)




[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
7th row
[60 61 62 63 64 65 66 67 68 69]
4th to 8th row
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]
value at the index 5,5= 44
5th column
[ 5 15 25 35 45 55 65 75 85 95]
2nd to 5th column
[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]
 [61 62 63 64]
 [71 72 73 74]
 [81 82 83 84]
 [91 92 93 94]]
